### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by kolbenhans** [RPiList/TarpitAn#5]
....>java -jar TarpitConv.jar

 Reading Log-File.
 Conversion.
 Writing Log-File.

 Process finished.

....>java -jar TarpitAn.jar
 Reading Data.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.lang.ClassLoader.findLoadedClass0(Native Method)
        at java.lang.ClassLoader.findLoadedClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:153)
        at MainKt.main(Main.kt:36)
        at MainKt.main(Main.kt)

**Comment by RPiList** [comment]
It's an Java Error, probably because of different java-versions. Greetings.
