### ISSUE TITLE
"main" java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by hookz23** [RPiList/TarpitAn#7]
java -jar TarpitAn.jar

 Reading Data.
 Writing Data.
Exception in thread "main" java.lang.ArithmeticException: / by zero
        at MainKt.analyse(Main.kt:165)
        at MainKt.main(Main.kt:44)
        at MainKt.main(Main.kt)

**Comment by RPiList** [comment]
Most likely an error in the logfile, caused by restarting/crashing tarpit.
